spring.datasource.url=jdbc:mysql://localhost:3306/college_rating_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=@njali#123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081

# For better error messages
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anjalibiradar222@gmail.com
spring.mail.password=zqgupvklwnlxslpq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App URLs
app.frontend.url=http://localhost:3000